# Generated by Django 4.2 on 2023-10-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
